### PR TITLE
Fixes #33 Thanks @ksuszka

### LINKED ISSUE #33: Not decaching children of modules
For some reason I can't get it to remove the children of a module. It just removes the top level module, leaving all children in place. Specifically, I have a module mymodule/index.js and a helper file mymodule/helper.js, index requires helper, but when I decache, the helper and all the node_modules remain in the cache.

Here is an example https://github.com/cutejs/decache-example

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by jupiter**

### CODE REVIEW

**Comment by jupiter** [comment]
I added #35 as this actually makes #32 show up during testing.

File: decache.js [hunk 1]
```diff
@@ -51,22 +51,20 @@ require.decache = function (moduleName) {
...
     var mod = require.resolve(moduleName);
+    const visited = {};
 
     // Check if the module has been resolved and found within
     // the cache no else so #ignore else http://git.io/vtgMI
     /* istanbul ignore else */
     if (mod && ((mod = require.cache[mod]) !== undefined)) {
         // Recursively go over the results
         (function run(mod) {
+            visited[mod.id] = true;
```
Comment (nelsonic) [inline decache.js]: I know updating a property on a `const` _works_ but do we _want_ to be mutating a constant?
or can we just use a `let` here?

File: decache.js [hunk 2]
```diff
@@ -51,22 +51,20 @@ require.decache = function (moduleName) {
...
     // Resolve the module identified by the specified name
     var mod = require.resolve(moduleName);
+    const visited = {};
 
     // Check if the module has been resolved and found within
     // the cache no else so #ignore else http://git.io/vtgMI
     /* istanbul ignore else */
     if (mod && ((mod = require.cache[mod]) !== undefined)) {
         // Recursively go over the results
         (function run(mod) {
```
Comment (MSala) [inline decache.js]: It should be:
`function run(module) {`

File: decache.js [hunk 3]
```diff
@@ -51,22 +51,20 @@ require.decache = function (moduleName) {
 require.searchCache = function (moduleName, callback) {
     // Resolve the module identified by the specified name
     var mod = require.resolve(moduleName);
+    const visited = {};
```
[the remark this answers is not in the document]
Comment (jupiter) [reply decache.js]: For compatibility, we should change to `var`.

File: decache.js (hunk 2 above)
Comment (jupiter) [reply decache.js]: `module` is already declared in the outside scope, so even if safe, it could cause confusion.

File: decache.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (nelsonic) [reply decache.js]: yeah, good shout! maybe `let's` stick to `var`. 😉

File: decache.js (hunk 2 above)
Comment (MSala) [reply decache.js]: True, but I am worried about line number 65, where we see 'module' and that way it is wrong. Pick another name but it needs to be corrected ;)

File: decache.js [hunk 4]
```diff
@@ -51,28 +51,26 @@ require.decache = function (moduleName) {
 require.searchCache = function (moduleName, callback) {
     // Resolve the module identified by the specified name
     var mod = require.resolve(moduleName);
+    var visited = {};
```
Comment (nelsonic) [inline decache.js]: `#retro` 😉

File: decache.js [hunk 5]
```diff
@@ -51,28 +51,26 @@ require.decache = function (moduleName) {
...
             // Go over each of the module's children and
             // run over it
-            mod.children.forEach(function (child) {
-                // Prevent infinite recursion
-                /* istanbul ignore next */
-                if (child.parent === mod) {
-                  return;
-                } else {
-                  run(child);
+            current.children.forEach(function (child) {
```
Comment (nelsonic) [inline decache.js]: clearer. 👍
